# Generated by Django 5.0.6 on 2024-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tags', max_length=255, verbose_name='Meta Keywords'),
        ),
    ]
